# -*- coding: utf-8 -*-
"""doppelmap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mLnAf1wudoFucn5r4uM-akL2EMbFPh3
"""

# CELL 0 — full GPU setup, run FIRST in a fresh runtime
!pip install -q insightface opencv-python-headless umap-learn scikit-learn plotly tqdm kagglehub
!pip uninstall -y -q onnxruntime onnxruntime-gpu       # remove whatever tagged along
!pip install -q "onnxruntime-gpu==1.22.0"              # CUDA-12 build, matches Colab

import torch                                           # pins Colab's cuDNN 9 into the process
import onnxruntime as ort
assert ort.get_device() == "GPU", "wrong ORT build"
assert "CUDAExecutionProvider" in ort.get_available_providers(), "no CUDA provider"
print("ORT", ort.__version__, "on", torch.cuda.get_device_name(0))

import onnxruntime as ort
print(ort.get_available_providers())   # must list 'CUDAExecutionProvider'

import os, ast, json, numpy as np, pandas as pd, cv2
from tqdm.auto import tqdm
from google.colab import drive
import kagglehub

drive.mount("/content/drive")
WORK = "/content/drive/MyDrive/doppelmap"      # everything durable lives here
os.makedirs(WORK, exist_ok=True)
path = kagglehub.dataset_download("abhikjha/imdb-wiki-faces-dataset")

import scipy.io
mat = scipy.io.loadmat(os.path.join(path, "imdb_crop", "imdb.mat"))["imdb"][0, 0]
df = pd.DataFrame({
    "full_path": [os.path.join(path, "imdb_crop", p[0]) for p in mat[2][0]],
    "gender": mat[3][0],
    "name": [n[0] if len(n) else None for n in mat[4][0]],
    "face_score": mat[6][0],
    "second_face_score": mat[7][0],
    "celeb_id": mat[9][0],
})
df["gender"] = df["gender"].map({0.0: "female", 1.0: "male"})   # NaN stays NaN
df = df.dropna(subset=["name"])
print(len(df), "rows,", df.celeb_id.nunique(), "celebrities")

TOP_N_CELEBS = 50000     # scale this up when the pipeline behaves
MAX_IMGS     = 500     # per celeb; consensus needs volume more than purity
FACE_MIN     = 1.0    # loose detector-quality floor (it is NOT identity confidence)

pool = df[df.face_score > FACE_MIN]
top = pool.name.value_counts().head(TOP_N_CELEBS).index
sel = (pool[pool.name.isin(top)]
       .sort_values("face_score", ascending=False)
       .groupby("name").head(MAX_IMGS))
print(len(sel), "images selected,", sel.name.nunique(), "celebrities")

import onnxruntime as ort
print(ort.get_available_providers())   # must list 'CUDAExecutionProvider'


from collections import deque
from concurrent.futures import ThreadPoolExecutor
from insightface.app import FaceAnalysis
from tqdm.auto import tqdm
import cv2, numpy as np, os

app = FaceAnalysis(name="buffalo_l",
                   allowed_modules=["detection", "genderage", "recognition"],
                   providers=["CUDAExecutionProvider"])
app.prepare(ctx_id=0, det_size=(320, 320))
# sanity: every "Applied providers" line above must say CUDA, not CPU

CACHE = f"{WORK}/emb_cache.npz"
img_emb = {}
if os.path.exists(CACHE):
    z = np.load(CACHE, allow_pickle=True)
    img_emb = dict(zip(z["k"].tolist(), list(z["v"])))
    print(f"resumed with {len(img_emb)} cached embeddings")

def save_cache():
    np.savez(CACHE, k=np.array(list(img_emb), dtype=object),
             v=np.array(list(img_emb.values())))

def process(i, img, gender, why):
    """Everything after decode: detect, pick center face, filter, embed."""
    if img is None:
        why["unreadable"] += 1; return
    faces = app.get(img)
    if not faces:
        why["no_face"] += 1; return
    h, w = img.shape[:2]
    f = min(faces, key=lambda f: ((f.bbox[0] + f.bbox[2]) / 2 - w / 2) ** 2
                               + ((f.bbox[1] + f.bbox[3]) / 2 - h / 2) ** 2)
    if f.det_score < 0.6:
        why["low_det"] += 1; return
    if isinstance(gender, str) and ("female" if f.sex == "F" else "male") != gender:
        why["gender_mismatch"] += 1; return
    img_emb[i] = f.normed_embedding.astype(np.float32)
    why["ok"] += 1

todo = [(i, r.full_path, r.gender) for i, r in sel.iterrows() if i not in img_emb]
why = {"unreadable": 0, "no_face": 0, "low_det": 0, "gender_mismatch": 0, "ok": 0}
load = lambda t: (t[0], cv2.imread(t[1]), t[2])

PREFETCH = 32                            # decoded images in flight (RAM-bounded)
with ThreadPoolExecutor(max_workers=8) as ex:
    it = iter(todo)
    q = deque(ex.submit(load, t) for _, t in zip(range(PREFETCH), it))
    done = 0
    with tqdm(total=len(todo)) as bar:
        while q:
            i, img, gender = q.popleft().result()
            nxt = next(it, None)
            if nxt is not None:
                q.append(ex.submit(load, nxt))
            process(i, img, gender, why)     # inference stays on this one thread
            done += 1; bar.update(1)
            if done % 2000 == 0:
                save_cache()
save_cache()
print(why)

SAME_PERSON = 0.35    # ArcFace same-identity floor
MIN_CONSENSUS = 0.5   # below this the gallery is majority-junk -> refuse

names, vecs, n_used, report = [], [], [], []
for name, g in sel.groupby("name"):
    ids = [i for i in g.index if i in img_emb]
    if len(ids) < 3:
        report.append((name, "too few embeddings", len(ids))); continue
    X = np.stack([img_emb[i] for i in ids])
    Ssim = X @ X.T
    medoid = Ssim.sum(1).argmax()              # most "typical" image = the person
    keep = Ssim[medoid] > SAME_PERSON
    if keep.mean() < MIN_CONSENSUS:
        report.append((name, "gallery contaminated", f"{keep.mean():.0%}")); continue
    v = X[keep].mean(0); v /= np.linalg.norm(v)
    names.append(name); vecs.append(v); n_used.append(int(keep.sum()))
E = np.stack(vecs)
np.savez(f"{WORK}/prototypes.npz", names=np.array(names), E=E, n_used=n_used)
print(f"{len(names)} prototypes (median {int(np.median(n_used))} images each)")
for r in report:
    print("  skipped:", r)

MIN_IMAGES = 5
keep = [i for i in range(len(names)) if n_used[i] >= MIN_IMAGES]
print(f"dropping {len(names) - len(keep)} thin prototypes")
names  = [names[i] for i in keep]
n_used = [n_used[i] for i in keep]
E = E[keep]
mu = E.mean(0); Ec = E - mu
Ec /= np.linalg.norm(Ec, axis=1, keepdims=True)
S = Ec @ Ec.T

DUP = 0.55
drop = set()
a_i, b_i = np.where(np.triu(S, 1) > DUP)
for a, b in zip(a_i, b_i):
    loser, winner = (a, b) if n_used[a] < n_used[b] else (b, a)
    drop.add(loser)
    print(f"drop {names[loser]:28s} = {names[winner]} ({S[a,b]:.2f})")
keep = [i for i in range(len(names)) if i not in drop]
names  = [names[i] for i in keep]
n_used = [n_used[i] for i in keep]
Ec = Ec[keep]; S = Ec @ Ec.T
print(f"{len(drop)} removed, {len(names)} remain")

def image_level(a, b, top=5):
    ga = [i for i in sel[sel.name == a].index if i in img_emb]
    gb = [i for i in sel[sel.name == b].index if i in img_emb]
    Xa, Xb = np.stack([img_emb[i] for i in ga]), np.stack([img_emb[i] for i in gb])
    C = Xa @ Xb.T
    flat = np.argsort(-C, axis=None)[:top]
    for f in flat:
        ia, ib = np.unravel_index(f, C.shape)
        print(f"{C[ia, ib]:.2f}", sel.loc[ga[ia], "full_path"].split("/")[-1],
              "<->", sel.loc[gb[ib], "full_path"].split("/")[-1])

image_level("Jennifer Aniston", "Tom Hanks")
image_level("Charlize Theron", "Scarlett Johansson")   # control: a real pair

# %% top pairs + neighbor lists (post-dedup)
LOOKALIKE_AT = 0.30
pct = lambda s: int(round(100 * np.clip((s - 0.25) / (0.55 - 0.25), 0, 1)))

a_i, b_i = np.where(np.triu(S, 1) > LOOKALIKE_AT)
edges = sorted(zip(a_i, b_i, S[a_i, b_i]), key=lambda t: -t[2])
connected = {i for a, b, _ in edges for i in (a, b)}
print(f"{len(edges)} pairs above {LOOKALIKE_AT} · "
      f"{len(names) - len(connected)} of {len(names)} with no match\n")

for i in range(len(names)):
    order = np.argsort(-S[i])[1:6]
    top = ", ".join(f"{names[j]} {S[i, j]:.2f}" for j in order)
    print(f"{names[i]:26s} -> {top}")

def similar(name, k=8):
    i = names.index(name)
    return [(names[j], round(float(S[i, j]), 3)) for j in np.argsort(-S[i])[1:k+1]]

import plotly.graph_objects as go
LOOKALIKE_AT = 0.30

N = len(names)
pct = lambda s: int(round(100 * np.clip((s - LOOKALIKE_AT) / (0.6 - LOOKALIKE_AT), 0, 1)))
if N < 100:
    from sklearn.manifold import MDS
    xy = MDS(2, dissimilarity="precomputed", random_state=42, normalized_stress="auto"
             ).fit_transform(np.sqrt(np.clip(2 - 2 * S, 0, None)))
else:
    import umap
    xy = umap.UMAP(n_neighbors=15, metric="cosine", random_state=42).fit_transform(E)

a_i, b_i = np.where(np.triu(S, 1) > LOOKALIKE_AT)
edges = sorted(zip(a_i, b_i, S[a_i, b_i]), key=lambda t: -t[2])
connected = {i for a, b, _ in edges for i in (a, b)}
ex, ey = [], []
for a, b, _ in edges:
    ex += [xy[a, 0], xy[b, 0], None]; ey += [xy[a, 1], xy[b, 1], None]

go.Figure([
    go.Scatter(x=ex, y=ey, mode="lines", hoverinfo="skip",
               line=dict(width=2, color="rgba(29,158,117,0.7)")),
    go.Scatter(x=xy[:, 0], y=xy[:, 1], mode="markers+text", text=names,
               textposition="top center", textfont=dict(size=10),
               marker=dict(size=9, color=["#1d9e75" if i in connected else "#9aa3af"
                                          for i in range(N)]),
               hovertemplate="%{text}<extra></extra>"),
]).update_layout(width=900, height=750, showlegend=False, xaxis_visible=False,
                 yaxis_visible=False, margin=dict(l=10, r=10, t=10, b=10)).show()

print(f"{len(edges)} lookalike pairs above {LOOKALIKE_AT} · "
      f"{N - len(connected)} people with no match")
for a, b, s in edges[:50]:
    print(f"  {names[a]} — {names[b]}: {pct(s)}%")

import matplotlib.pyplot as plt
from PIL import Image

def inspect(name, cols=8):
    g = sel[sel.name == name]
    ids = [i for i in g.index if i in img_emb]
    X = np.stack([img_emb[i] for i in ids]); Ssim = X @ X.T
    med = Ssim.sum(1).argmax(); sims = Ssim[med]
    order = np.argsort(-sims)
    fig, axes = plt.subplots((len(ids)-1)//cols+1, cols, figsize=(2*cols, 2.3*((len(ids)-1)//cols+1)))
    for ax in np.ravel(axes): ax.axis("off")
    for ax, j in zip(np.ravel(axes), order):
        ax.imshow(Image.open(g.loc[ids[j], "full_path"]))
        kept = sims[j] > SAME_PERSON
        ax.set_title(f"{sims[j]:.2f}{'' if kept else ' ✗'}", fontsize=8,
                     color="green" if kept else "red")
    plt.suptitle(name); plt.tight_layout(); plt.show()

for n in ["Jennifer Aniston", "Tom Hanks", "Emily Deschanel", "Zooey Deschanel"]:
    inspect(n)







